# Generated by Django 5.0.6 on 2024-07-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0002_alter_autor_nacionalidad_alter_autor_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='apellido',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
