# Generated by Django 5.0.6 on 2024-07-30 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0004_remove_libro_fecha_publicacion_libro_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='nombre',
        ),
    ]
