# Generated by Django 5.0.6 on 2024-08-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0006_editorial_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
